import Link from 'next/link'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms & Conditions',
  description: 'Terms and Conditions for Shahnaz Salon services, bookings, and payments.',
}

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gray-50 py-8 px-4">
      <div className="max-w-3xl mx-auto bg-white rounded-xl shadow-sm border border-gray-200 p-6 sm:p-8">
        <h1 className="text-2xl sm:text-3xl font-bold text-gray-900 mb-2">
          Terms &amp; Conditions
        </h1>

        <div className="prose prose-gray prose-sm max-w-none space-y-6 text-gray-700">
          <p>
            This document is an electronic record in terms of the Information Technology Act, 2000 and rules thereunder as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p>
            This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of the domain name (&quot;Website&quot;), including the related mobile site and mobile application (hereinafter referred to as the &quot;Platform&quot;).
          </p>
          <p>
            The Platform is owned and operated by the Platform Owner (details provided at the end of this document).
          </p>
          <p>
            Your use of the Platform, its services, and tools are governed by the following terms and conditions (&quot;Terms of Use&quot;) including the applicable policies which are incorporated herein by way of reference. If you transact on the Platform, you shall be subject to the policies that are applicable for such transactions. By mere use of the Platform, you shall be contracting with the Platform Owner, and these Terms of Use including the policies constitute your binding obligations.
          </p>
          <p>
            Any terms and conditions proposed by you which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without prior notice. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
          </p>
          <p>
            For the purpose of these Terms of Use, wherever the context so requires, &quot;you&quot;, &quot;your&quot; or &quot;user&quot; shall mean any natural or legal person who has agreed to become a user/buyer on the Platform.
          </p>
          <p className="font-semibold text-gray-900">
            ACCESSING, BROWSING, OR OTHERWISE USING THE PLATFORM INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE. PLEASE READ THEM CAREFULLY BEFORE PROCEEDING.
          </p>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Key Terms</h2>
            <ol className="list-decimal pl-6 space-y-4">
              <li>
                <strong>Eligibility &amp; Registration</strong><br />
                To access and use the Services, you agree to provide true, accurate, and complete information during and after registration, and you are responsible for all acts done through the use of your registered account.
              </li>
              <li>
                <strong>Accuracy of Information</strong><br />
                Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness, or suitability of the information and materials on this Platform. You acknowledge that such information may contain inaccuracies or errors, and we exclude liability for such inaccuracies to the fullest extent permitted by law.
              </li>
              <li>
                <strong>Use of Services</strong><br />
                Your use of our Services and Platform is solely at your own risk. You must independently assess and ensure that the Services meet your requirements.
              </li>
              <li>
                <strong>Intellectual Property</strong><br />
                The contents of the Platform (including but not limited to design, layout, graphics, and text) are proprietary. You do not acquire any rights to our intellectual property.
              </li>
              <li>
                <strong>Prohibited Use</strong><br />
                You agree not to use the Platform or Services for unlawful purposes or in violation of Indian or local laws.
              </li>
              <li>
                <strong>Links to Third Parties</strong><br />
                The Platform may contain links to third-party websites. Accessing these will be governed by the terms of use and privacy policies of such third parties.
              </li>
              <li>
                <strong>Legal Relationship</strong><br />
                Initiating a transaction constitutes a legally binding contract between you and the Platform Owner.
              </li>
              <li>
                <strong>Indemnity</strong><br />
                You agree to indemnify and hold harmless the Platform Owner, affiliates, and employees against claims, damages, or penalties arising out of your breach of these Terms.
              </li>
              <li>
                <strong>Limitation of Liability</strong><br />
                In no event will the Platform Owner be liable for indirect, incidental, or consequential damages. Our liability shall not exceed the amount paid by you for the Services giving rise to the claim, or INR 100, whichever is less.
              </li>
              <li>
                <strong>Force Majeure</strong><br />
                We are not liable for failure to perform obligations due to events beyond our control.
              </li>
              <li>
                <strong>Governing Law &amp; Jurisdiction</strong><br />
                These Terms shall be governed by the laws of India. All disputes shall be subject to the exclusive jurisdiction of the courts specified in the Company Details section below.
              </li>
              <li>
                <strong>Communication</strong><br />
                All concerns or communications relating to these Terms must be directed to the contact details provided in the Company Details section.
              </li>
            </ol>
          </section>

          <section className="mt-8 pt-6 border-t border-gray-200">
            <h2 className="text-lg font-semibold text-gray-900 mb-3">Company Details</h2>
            <p>
              <strong>Domain Name (Website):</strong>{' '}
              <a href="https://www.shahnazsalonsasaram.com/" target="_blank" rel="noopener noreferrer" className="text-primary-600 hover:underline">
                https://www.shahnazsalonsasaram.com/
              </a>
            </p>
            <p><strong>Company Name (Platform Owner):</strong> SHAHNAZZ BEAUTY PARLOUR</p>
            <p><strong>Registered Office Address:</strong> Sasaram, Bihar</p>
            <p><strong>Contact:</strong> <a href="tel:+918877799982" className="text-primary-600 hover:underline">+91 8877799982</a></p>
          </section>
        </div>

        <div className="mt-8 pt-6 border-t border-gray-200 flex flex-wrap gap-4">
          <Link
            href="/privacy"
            className="inline-flex items-center text-primary-600 font-medium hover:underline"
          >
            Privacy Policy
          </Link>
          <Link
            href="/refund"
            className="inline-flex items-center text-primary-600 font-medium hover:underline"
          >
            Refund &amp; Cancellation
          </Link>
          <Link
            href="/"
            className="inline-flex items-center text-primary-600 font-medium hover:underline"
          >
            ← Back to home
          </Link>
        </div>
      </div>
    </div>
  )
}
